telegram:
  api_id: 24512494
  api_hash: "965ff313790ad8d1971a8209c8dfcf85"
  token: "6287093697:AAGW14tCLi53eJrzGh-zx1C4WDI8hqqZX5U"
  lang_code: !!str "en"
  max_upload_tasks: 50
  allowed_users:
    - id:5193168915
      send_startup_message: !!bool True
      upload:
        upload_video_file: !!bool True
        upload_video_max_file_size: 2147483
        forward_to_group: !!bool False
        forward_group_id: -00000000000
        silent: !!bool False
        video_caption:
          include_title: !!bool True
          include_filename: !!bool False
          include_link: !!bool True
  api:
    upload_video_file: !!bool True
    upload_video_max_file_size: 2147483648
    upload_to_chat_ids:
      - 00000000000
      - -00000000000
    silent: !!bool False
    video_caption:
      include_title: !!bool True
      include_filename: !!bool False
      include_link: !!bool True
ytdlp:
  version_check_enabled: !!bool True
  version_check_interval: 86400
  notify_users_on_new_version: !!bool True
